### ISSUE TITLE
[docs] Method for debugging in IntelliJ

### ISSUE THREAD

**Issue by BigBallard** [tauri-apps/tauri-docs#1053]
I see in the documents there some method to debug with breakpoints in VSCode, however, I do not see anything regarding IntelliJ or CLion. Is there a well known method for running tauri in debug mode within IntelliJ using their configurations? I am at a point now where this is greatly needed over println everywhere.

**Comment by JonasKruckenberg** [comment]
Debugging a Tauri app isn't different from debugging any other Rust project, so following this official CLion guide in how to setup debugging should get you 90% of the way there

**Comment by JonasKruckenberg** [comment]
Had a fun time today playing around with CLion after quite a while and wrote up a guide to setup debugging with CLion, hope this helps you and others. Maybe you can give a quick feedback if this guide is missing anything @DallasP9124

**Comment by BigBallard** [comment]
@JonasKruckenberg thank you very much! Out of curiosity, I see that the majority of developers use CLion for the rust side of development. Is there a notable reason for this? I am new to compiled languages so maybe there is something I don't get.

**Comment by FabianLars** [comment]
CLion has a few more Rust features than the other IntelliJ IDEs, see https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#compatible-ids
Also i guess C/C++ support is nice for many low-level Rust devs since FFI is not as uncommon as i'd like 😅 
And many devs are probably already coming from a C / compiled language background so they basically just stick with what they know idk

**Comment by JonasKruckenberg** [comment]
stupidly enough CLion also has surprising amounts of support for JavaScript projects...
