### ISSUE TITLE
Create Tauri 2.0 CLI Reference

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#1363]
In the 1.0 documentation we use this to document the Tauri CLI: https://github.com/tauri-apps/tauri-docs/blob/dev/.scripts/generate-cli-doc.js

This relies on having upstream compiled which is a bit annoying from a CI/CD perspective. Is there a way we can write this information in a JSON format upstream so that we can just pull it directly and format it here? Or this might be something updated so infrequently that we opt for manually writing it instead.

Edit: I'd actually prefer starting simple and just making a `.md` file specifically for this since it doesn't change much at all over time.

**Comment by FabianLars** [comment]
I copied the v1 approach into [here](https://github.com/tauri-apps/tauri-docs/blob/docs/cli/src/content/docs/2/reference/cli.mdx) so we can have something to look for this question.

I'm a bit unsure how we want to handle sub commands. I don't think the approach used in v1 is the best fit but i can't think of anything much better. For example `tauri android` looks fine as is imo, so one section for all sub commands but the plugins commands i think are better suited to have a section each beacuse a) they are all pretty different to a point i feel like it's weird that they are in one, like `plugin add` vs all the rest basically (the "rest" is about modifying the current plugin project while plugin add is about adding a plugin to the current non-plugin project) and b) because some of these subcommands have subcommands

Also i'm a bit unsure about the wanted level of verbosity, do we want to keep it fairly simple as it is now, though i'd like to convert it into tables like here https://vitejs.dev/guide/cli.html, or do we want it a bit more text-like and split-up like how astro does it https://docs.astro.build/en/reference/cli-reference/

----

I think i shouldn't have started with this and let you handle it 😂

**Comment by lorenzolewis** [comment]
Going to pick up this convo over on the PR @FabianLars

**Comment by lorenzolewis** [comment]
Closed by #1365 , not worried about automation right at this point with how infrequently this changes.
