### ISSUE TITLE
[docs] problem with the very first tutorial

### ISSUE THREAD

**Issue by praksharma** [tauri-apps/tauri-docs#1422]
OS: Ubuntu 20.04

So I am a beginner. I was going through the very [first tutorial](https://tauri.app/v1/guides/getting-started/setup/html-css-js/) with HTML only. I decided to use Rust with cargo, so didn't install `npm`.  Also, on the [prerequisites](https://tauri.app/v1/guides/getting-started/prerequisites) pages it is not mentioned that `npm` is needed. 
## First problem 
The `tauri.conf.json` includes the following lines.

```
{
  "build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "npm run dev",
    "devPath": "../ui",
    "distDir": "../ui"
  },
```
This example shouldn't require `npm`, also I never installed its so I was getting this error.
```sh
╰─ cargo tauri dev                                                           ─╯
     Running BeforeDevCommand (`npm run dev`)
sh: 1: npm: not found
       Error The "beforeDevCommand" terminated with a non-zero status code.
```
These changes fixed the issue.
```
 "beforeBuildCommand": "",
 "beforeDevCommand": "",
```

## Second problem
i was getting compile error.
```sh
error: proc macro panicked
 --> src/main.rs:6:10
  |
6 |     .run(tauri::generate_context!())
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: The `devPath` configuration is set to `"../ui"` but this path doesn't exist

error: could not compile `app` (bin "app") due to previous error
```
I realised that the path should be relative to `src-tauri` directory. So it should be either 
```
"devPath": "../",
"distDir": "../",
```
or 
```
"devPath": "../../ui",
"distDir": "../../ui",
```

After these changes I could compile the app.
![image](https://github.com/tauri-apps/tauri/assets/70601302/a458a7a9-9995-4513-bf50-57ccb6efe676)

I know these are very basic things. But may be frustrating for beginners. I wish this was already mentioned in the tutorial.

**Comment by NoxFly** [comment]
<h2>First error :</h2>

In the tutorial, it is well mentionned to leave these two options __blank__, and when you execute it, it is pre-filled with a path. You have to delete these before pressing the return key.

![image](https://github.com/tauri-apps/tauri-docs/assets/32705400/628d072e-0813-46ee-bf68-4c4cc9a68051)

What we currently have pre-filled in our console is not blank : 
![image](https://github.com/tauri-apps/tauri-docs/assets/32705400/5fcdf6f5-b363-4043-b3e4-2a738d909868)

<h2>Second error :</h2>

This didn't happened to me (tried today). I got the same error, but because I forgot to create the `ui/` folder with the `index.html` inside. Once I did that, everything was fine. I just had to write `../ui` in the `tauri init` command (previous step), as written in the official documentation.

**Comment by hiankun** [comment]
To make the `../ui` work as mentioned in the tutorial, the directory structure has to be something like this:
```
my_app/
├── src-tauri
│   ├── icons
│   ├── src
│   └── target
└── ui
```

The tutorial is confusing.
