### ISSUE TITLE
I would like to translate read.me

### ISSUE THREAD

**Issue by Oscar-IA-68** [tauri-apps/tauri-docs#1593]
### 📋 Explain your issue

Hi, I noticed that the repositories have no translations. I would like to translate the README into Spanish, but I haven't seen any tasks related to internationalization (i18n) for the repositories.

**Comment by lorenzolewis** [comment]
Hi @Os-688 ! Is this for the README in this repo (the docs repo), or is this for other repos in the Tauri organization? We prefer doing translations on the content here in this docs repo as we have the tooling setup to support translations. We could always add links to any repo READMEs to direct users to the website for a specific language so that they're guided in a place with their preferred language.

**Comment by Oscar-IA-68** [comment]
Well actually I was referring to both. I understand that it is preferred in this repository because it is already enabled to do so. I would like to make the translation for the Spanish language.

**Comment by simonhyll** [comment]
@Os-688 Hey! Are you still interested in doing some translational work? If so feel free to reach out to us in the #docs channel on Discord!
I'll close this issue not because we're not interested but because it adds to the backlog. 😅
