### ISSUE TITLE
Fix formatting issues

### ISSUE THREAD

**Issue by simonhyll** [tauri-apps/tauri-docs#2355]
One or two issues have snuck into the codebase, someone should fix them.

**Comment by FabianLars** [comment]
I have a local branch locally where i'm working on this but i wanna finish https://github.com/tauri-apps/tauri-docs/pull/2313 beforehand

**Comment by FabianLars** [comment]
Okay so that escalated quite a bit, the mentioned branch simply removed broken mdx files from .prettierignore and used inline comments to make prettier ignore the blocks that break (which in most cases actually ended up being the whole file due to missing content).

Because i was looking at biome (which doesn't support markdown) a few days ago i thought it may be a good idea to look into an alterantive formatter for the mdx files (since prettier probably won't support mdx this century https://github.com/prettier/prettier/issues/12209 ) and really the only thing there is, is remark (with remark-lint etc). It indeed can format what prettier struggles with but it fails in other places. I don't have the time nor energy (nor the knowledge) to create our own remark plugin(s) for that so i scrapped the remark approach too.

The workflow isn't failing anymore so i'm closing this.
