### ISSUE TITLE
[docs] bad links about plugins🤔

### ISSUE THREAD

**Issue by montmorill** [tauri-apps/tauri-docs#2475]
### Question you want answered

-

### Where did you look for an answer?

-

### Additional context

There are some bad links that leads to an unexists page on GitHub such as:
- `https://github.com/tauri-apps/plugins-workspace/tree/plugins/biometric` at `https://v2.tauri.app/plugin/biometric/`
-  `https://github.com/tauri-apps/plugins-workspace/tree/plugins/nfc` at `https://v2.tauri.app/plugin/nfc/`

And also, there are many other bad links lie in almost everywhere.

I'm really sad about this.

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by vasfvitor** [comment]
thanks for reporting, I'm sorry you had that experience

if you need, you can find the plugin links in this repo, for the guides that are still missing on the docs https://github.com/tauri-apps/plugins-workspace

and just in case the biometric guide PR https://github.com/tauri-apps/tauri-docs/pull/2395 can give you some extra info. but it still to be reviewed.


> And also, there are many other bad links lie in almost everywhere.

could you please elaborate a bit? because they could be easily fixable if they're from references or other autogenerated pages.

**Comment by vasfvitor** [comment]
No reply, I can't reproduce the current issue, and multiple url fixes were done at https://github.com/tauri-apps/tauri-docs/pull/2802
