### ISSUE TITLE
[docs] Supported windows versions?

### ISSUE THREAD

**Issue by andreas-mausch** [tauri-apps/tauri-docs#25]
Hi there,

I've just tried to build my first app via tauri.

I've used a VM with Windows 7 and installed all the necessary tools (uff!).

Now I did `npm run build`, `tauri build`, it exited without any errors and gave me a .exe. Hooray!

However, at startup I see this error:

![tauri-error-win7](https://user-images.githubusercontent.com/1736847/75035321-807e6b00-54af-11ea-9bd9-9477d2caffb9.png)

Which made me think: Well, maybe you guys support Windows 10 only?
I couldn't find anything in the docs about supported versions.

Btw: I was able to execute the .exe on a Win10 box, but I only see a white screen there. That's a different issue, most likely I made a mistake somewhere.

Linux build runs perfectly.
Thank you for creating tauri. :)

**Comment by CrashLaker** [comment]
Hi guys.

I just started using tauri.
I'm having the same issue on windows servers (2016, 2019) which I guess doesn't come with edge or the engines installed.

So opening in windows server 2016 gives me this:
![image](https://user-images.githubusercontent.com/4432491/108712126-17cc3300-74f5-11eb-90cc-6c0ef66c9157.png)

In windows server 2019 only shows a blank screen.

Unless I install the step 7 (Optional WebView2 (Chromium)) described in the tutorial here https://tauri.studio/en/docs/get-started/setup-windows

Problem is that MicrosoftEdgeWebView2RuntimeInstaller weights ~95MB which now makes it the same size of electron with 2 install steps.

Am I doing something wrong?

edit:
Hi @nothingismagick could you help me where do I put the `edge active false` in `tauri.conf.json`.

`ERROR: tauri.conf.json > tauri has unknown property edge`

`ERROR: tauri.conf.json > tauri > bundle has unknown property edge`

**Comment by nklayman** [comment]
WebView2 is the only option for Windows versions <10 (besides installing Edge manually). The next Tauri release will drop support for EdgeHTML anyways, and it will create installers that can automatically download WebView2 if the user doesn't have it installed already, supporting windows versions 7-10. While the installer is quite large, Windows will ship with it preinstalled soon and it only needs to be installed once across all WebView2 apps. Right now it's unfortunate, but soon most people will have it preinstalled. Also, I don't think that we support EdgeHTML now, and we for sure won't in the next release, so I recommend avoiding that.

EDIT: It's 2021, not 2020 :facepalm:. This is a very old issue, that's why Denjell said we supported MSHTML. Everything else still applies though.

**Comment by CrashLaker** [comment]
Hi @nklayman, thank you for your reply.
I'm not familiar about all these web engines (EdgeHTML, WebView2, MSHTML). Is there a place you recommend looking for further understanding?

Also as I've mentioned above my demo app just breaks when trying to use WebView2 (`WebView2Loader.dll`). Is this expected? How could I work around this?

When you say Tauri will be dropping support for EdgeHTML you mean `MicrosoftEdgeWebView2RuntimeInstaller`?

regards,
C.

**Comment by nklayman** [comment]
MSHTML is the old, Internet-Explorer based WebView. EdgeHTML is a newer, Edge-based WebView. WebView2 is the latest, Chromium-Edge based WebView, and will be exclusively used by Tauri from the next release on.

As for the .dll issue, I'm not sure what could be wrong. It just works fine for me as long as I've [downloaded it](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) first. The next version of Tauri will change how the dll is loaded and will be much more stable, so that should fix your issue.

**Comment by CrashLaker** [comment]
I see thank you for the info @nklayman 

As older windows such as srv 2016 eol is due to 2022 (mainstream) and 2027 (extended) i suppose they'll remain around.

for the time being is it possible to use an older version of tauri + mshtml?

**Comment by nklayman** [comment]
I'd advise against using an older Tauri version. It'd probably be better to use the unreleased code from the dev branch which uses the new Webview2 loading process. That should work on older windows versions as long as they have Webview installed. See the .github/contributing.md file for instructions on using the development branch. However, the current Tauri version is supposed to work with webview2 as well, so it may be an issue with your installation.

**Comment by Shivang-idrive** [comment]
> Hi @andreas-mausch - had a busy week and didn't find a moment to get back to you. We will never be shipping apps that officially work with operating systems beyond their EOL. Windows 7 has been deprecated in January, and we cannot in good faith retain our security posture where vendors can't keep up with us.
> 
> Nevertheless, we do still enable the MSHTML mode of web-view, although there are conflicting reports about it really working. To do this you will need to update the `tauri.conf.json` and make sure that edge.active = false:
> 
> ```
>     "edge": {
>       "active": false
>     },
> ```

Where to put edge.active=false in tauri.config as It is giving error.

**Comment by FabianLars** [comment]
@Shivang-idrive This issue is outdated and describes Tauri's alpha version. The specific config you asked about does not exist (anymore).

**Comment by Shivang-idrive** [comment]
@FabianLars  Facing same issue as stated above in windows 7 both 32 and 64 bit and in windows 8.1 32 bit.
Any solution for this?
