### ISSUE TITLE
Getting started documentation needs work

### ISSUE THREAD

**Issue by designingSparks** [tauri-apps/tauri-docs#263]
This is still a problem. After following the introduction [here](https://tauri.studio/en/docs/development/intro), the next logical step is to set up a project. From the website, the next step after setup is Tauri Integration. This page here needs serious work for newcomers: https://tauri.studio/en/docs/development/integration
For example, it tells you to start by entering at the command line: `yarn tauri init`
At this step, you are prompted to enter in the address of the dev server. What?! In the documentation there has been no mention of a webserver!
Also the difference between adding to an existing React/Vue/Svelte project should be made clear right from the beginning as opposed to setting everything up manually.

**Comment by kornelski** [comment]
Indeed. The dev server thing surprised me too. I've entered `localhost`, and then the app wouldn't start, because apparently that isn't valid. But the tutorial didn't say what format it wants it in, and what even the server is used for. Is it even used? I thought the app logic was in Rust, not Node.js.

**Comment by lorenzolewis** [comment]
We've done a lot of updates to the guides since this issue, going to close it. If you have any additional feedback then more than happy to hear how we can improve :)
