### ISSUE TITLE
Add guide: Tauri + React

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri-docs#443]
# TODO

Explain how to use Tauri with a React frontend, show a few examples using various Tauri APIs and give some tips on configuration.

# Details

## Setup
- install react
- link to react getting started

## Development
- basic example
- show how to import tauri functions
- how how to use `events.listen` with `useEffect`

## SSG
- ssg is possible with react
- renderToString and hydrate
- link to vite SSG guides

**Comment by vanvuongngo** [comment]
How about using Qwik framework (MR: https://github.com/tauri-apps/tauri-docs/pull/1233) with the React integration (https://qwik.builder.io/docs/integrations/react/)?

Tauri + Qwik + React

**Comment by FabianLars** [comment]
tbh i feel like this is already covered by the vite guide since create-react-app seems to get less popular by the day.
On top of that we have a nextjs guide, and a "Integrate into whatever framework" guide which even used create-react-app.
And on top of that now also comes Qwik with React support so let's just close this issue for now 💪
