### ISSUE TITLE
FAQ: Brew and Potential Conflicts with Tauri

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#674]
Installation issue because of Brew (see https://discordapp.com/channels/616186924390023171/987144563388997662/987298158692413440 for more details) to add the FAQ.

**Comment by lorenzolewis** [comment]
@amrbashir and @Laegel could you give a bit more context for this? So is the issue if brew is install on linux in general? Or just if you installed tauri via brew? And what are the mitigation steps? I saw uninstalling brew but is that the only option?

What would the errors look like for this? Dependency issues?

We should also have a link in the Quick Start pages to this specific FAQ entry

**Comment by amrbashir** [comment]
@FabianLars has more knowledge of this issue, but I will try my best to explain this.

The system dependencies for tauri on Linux, are usually installed through the package manager like `api` and usually includes `pkg-config` (a utility to find libs on the system) and if you install `brew` it has its own `pkg-config` but it somehow also overrides the `pkg-config` installed through the package manager. Now when you try to build a tauri app, it will try to invoke `pkg-config` and it will end up invoking the one from `brew` but since `brew` wasn't used to install tauri's dependencies, it won't find them, hence the error.

The solution can be one of two:
1. remove `brew`
2. set the `PKG_CONFIG_PATH` environment variable to point to the correct `pkg-config` before trying to build a tauri app

**Comment by lorenzolewis** [comment]
What would an error message look like for this so that I can put it in there. Something like this?:

```
error: failed to select a version for the requirement `tauri = "^1.0.0"`
```

This is only relevant on Linux if using brew since it messes with the package manager if I'm reading this right.

**Comment by FabianLars** [comment]
Nah, the errors are wayyyy more wild. One example would be this one: <https://gist.github.com/Olyno/536e6dd2b64f8b9903b1c6353181c98a#file-logs-properties-L350>

**Comment by lorenzolewis** [comment]
So it can happen at any point in the dev lifecycle. fun. Maybe just having something titled "Brew Conflict on Linux" or similar then and not even try to go beyond that. I was thinking "what would someone google to get to the right page" but maybe there isn't a magic combo
