### ISSUE TITLE
[docs] What's recommended browserlist for tauri?

### ISSUE THREAD

**Issue by mokeyish** [tauri-apps/tauri-docs#696]
Hi,
From the readme, we known that tauri  leveraging WebKit on macOS, WebView2 on Windows and WebKitGTK on Linux.
But what's recommended browserlist for tauri?

I use [autoprefixer](https://github.com/postcss/autoprefixer ) to add vendor prefixes to generated css automatically. It needs browserslist .

**Comment by nothingismagick** [comment]
That's a really good question. we've talked about this before, and actually providing a "tauri" set to browserlist. Happy to have the discussion here

**Comment by FabianLars** [comment]
hmm, a pretty safe one for macOS 10.15+ should be `"defaults, not IE 11, safari >13, not op_mini all"`. For macOS 10.13+ this would need `safari >11` instead.

Since we don't have mobile support yet you could exclude them too, but i don't expect much of a difference.

_Edit:_ Alternatively you can make every "normal" webdev cry by using: `"safari >13, last 2 chrome versions"` (or `safari >11` as mentioned above), which is a bad idea for normal web targets but should work just fine in tauri apps.

_Edit2:_ Because of Linux i wouldn't go higher than safari 13 even if you want to target only newer macOS versions.

**Comment by caryxiao** [comment]
Mark.

**Comment by JonasKruckenberg** [comment]
In the [vite getting started guide](https://tauri.app/v1/guides/getting-started/setup/vite) we recommend `target: ['es2021', 'chrome97', 'safari13'],`

It was the result of some previous discussions and research and seems to be pretty much what you came up with too
