### ISSUE TITLE
Tauri 系列 - 打造属于自己的下一代跨端应用

### ISSUE THREAD

**Issue by lencx** [tauri-apps/tauri-docs#786]
推荐一份中文版《Tauri 系列》实战指南。虽然 Tauri 已经发布 v1.0 版本，但是中文可参考资料却寥寥无几。我正在基于 Tauri 开发一款工具集（各种小功能），通过写文章的形式来记录开发过程中遇到的各种问题，有配套代码仓库可供参考。希望这些文章可以帮助更多想入门 Tauri 的人，壮大 Tauri 的中文社区。

文章地址：[Tauri 系列](https://github.com/lencx/OhMyBox/discussions/categories/blog?discussions_q=category%3ABlog+label%3A%22Tauri+%E7%B3%BB%E5%88%97%22)
代码仓库：[lencx/OhMyBox](https://github.com/lencx/OhMyBox)

**Comment by lorenzolewis** [comment]
Hey @lencx thank you for putting these resources together! Had to do a bit of Google translate so hope I understood everything correctly from the original issue. 

I'd recommend putting in a pull request to https://github.com/tauri-apps/awesome-tauri with the resources you included so that more people can benefit from it (just be sure to provide a bit of context in English in your PR). 

If there are specific gaps that we could do to help with the docs then feel free to let us know. We wrote them in English first but then they go through Crowdin where the community can translate them https://tauri.crowdin.com
