### ISSUE TITLE
`cargo upgrade` is not the correct command in docs

### ISSUE THREAD

**Issue by thadguidry** [tauri-apps/tauri-docs#819]
Example:
```
E:\GitHub Repos\openrefine-tauri\src-tauri>cargo upgrade
error: no such subcommand: `upgrade`

        Did you mean `update`?

E:\GitHub Repos\openrefine-tauri\src-tauri>cargo update
    Updating crates.io index
    Updating anyhow v1.0.56 -> v1.0.61
    Removing async-broadcast v0.3.4
    Removing async-channel v1.6.1
<snip>
```

**Comment by FabianLars** [comment]
copy paste from discord:
The reason why it's upgrade and not update, is because update can't update pre-release versions reliably, and in that context, can't modify the Cargo.toml file.

See https://github.com/tauri-apps/tauri-docs/pull/670.

We'll look into removing that whole section from that page because i don't think it fits in there.
