### ISSUE TITLE
[docs] Seem a mistake in doc

### ISSUE THREAD

**Issue by willser** [tauri-apps/tauri-docs#928]
Hi team.
I am starting to learn to use `tauri`I read this [website](https://tauri.app/v1/guides/getting-started/setup/html-css-js) and get those :
```
Please note that you do not need to follow the rest of this guide if you use create-tauri-app, but we still recommend reading it to understand the setup.
```
So I just run fllowing command:
```
cargo install create-tauri-app
cargo create-tauri-app
```
And I got those result:
```
Done, Now run:
  cd tauridemo
  cargo tauri dev
```
I did it.But I got a error :
```
> cargo tauri dev
error: no such subcommand: `tauri`
Did you mean `miri`?
```

I had to read follow the rest of this guide.And I noticed there a command which is `cargo install tauri-cli`.I tried it.After install,I run 
`cargo tauri dev`,it works,it begin build!
So I think there a mistake in doc or `cargo install create-tauri-app` doesn't install `tauri-cli` in expected(I don't think so,because I got no error when runing it).

**Comment by FabianLars** [comment]
So the sentence about skipping the rest of the guide was mostly with create-tauri-app v1 in mind which didn't have the cargo-only setup.
The thing is, i'm not sure how to include the cargo "edge case", especially since create-tauri-app tells you to install it:
```
Please follow https://tauri.app/v1/guides/getting-started/prerequisites to install the needed prerequisites, if you haven't already.
You also need to install tauri-cli (cargo install tauri-cli)

Done, Now run:
  cd tauri-app
  cargo tauri dev
```
^ This is the output after `cargo create-tauri-app` and i'm not sure how to make it clearer in the docs without making it harder for the people who don't use the cargo cli 🤔

**Comment by willser** [comment]
@FabianLars My bad.I didn't read the return of the first command carefully.There is nothing missing about this command.
